<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://www.example.org" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://TargetNamespace.com/createCSVFile" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/InventoryManagerPOC.xsd"/>
            <oracle-xsl-mapper:rootElement name="response" namespace="http://www.example.org"/>
            <oracle-xsl-mapper:param name="csvFileInput"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/nxsd_schema1.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/createCSVFile"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE JUN 27 17:21:22 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Root-Element>
         <xsl:for-each select="/ns0:response/ns0:inventoryResponseDataList">
            <tns:Inventory>
               <tns:C1>
                  <xsl:value-of select="ns0:DC_CODE"/>
               </tns:C1>
               <tns:C2>
                  <xsl:value-of select="ns0:BIN_CODE"/>
               </tns:C2>
               <tns:C3>
                  <xsl:value-of select="ns0:ITEM"/>
               </tns:C3>
               <tns:C4>
                  <xsl:value-of select="ns0:UNIT"/>
               </tns:C4>
               <tns:C5>
                  <xsl:value-of select="ns0:REASON"/>
               </tns:C5>
               <tns:C6>
                  <xsl:value-of select="ns0:SELL_BY_DATE"/>
               </tns:C6>
            </tns:Inventory>
         </xsl:for-each>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
